environment:
  ATOM_SHELL_INTERNAL_RUN_AS_NODE: 1
	nodejs_version: "4.1.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g gulp mocha

build_script:
  - .\scripts\npm.bat install --force
  - gulp electron
  - gulp compile

test_script:
  - mocha
